export const researchStories = [
  {
    id: 'good-life',
    topic: 'The good life',
    title: 'What does a life of learning new things offer?',
    description: 'A good life can be comfortable and purposeful. But where do unfamiliar experiences, unanswered questions, and changes of perspective fit in?',
    image: '/images/bookstore-browsing.webp',
    alt: 'People browsing books and discovering things to read.',
    width: 1000, height: 669,
  },
  {
    id: 'division-of-labor',
    topic: 'Work & curiosity',
    title: 'When does “not my job” become “not worth knowing”?',
    description: 'Dividing work helps us become efficient. My experiments ask what happens to curiosity when people take on a narrow role—even their curiosity about things outside the task.',
    image: '/images/division-of-labor-experiments.webp',
    alt: 'Bicycle assembly and trivia tasks used to study specialization and curiosity.',
    width: 780, height: 536,
    figure: true,
  },
  {
    id: 'occupational-herding',
    topic: 'Inequality & aspirations',
    title: 'Why do so many children dream of the same jobs?',
    description: 'Exploring also means imagining who we might become. I study why young people’s ambitions crowd into a few popular occupations, and how inequality may narrow the futures they consider.',
    image: '/images/career-possibilities.webp',
    alt: 'An illustrative photograph of children dressed for different occupations.',
    width: 900, height: 600,
  },
  {
    id: 'places',
    topic: 'Cities & new experiences',
    title: 'Can a city make room for curiosity?',
    description: 'A bookstore, a museum, a place you did not plan to visit. I study where people find new perspectives—and whether having those places close together makes a difference.',
    image: '/images/rich-places-san-francisco.webp',
    alt: 'A map of clustered psychologically rich places in San Francisco.',
    width: 1800, height: 1117,
  },
  {
    id: 'llm-steering',
    topic: 'AI & conversation',
    title: 'Can a conversation make us curious again?',
    description: 'What would an AI conversation look like if it put psychological richness first? We steer a model’s internal representations to test whether a conversation can renew interest in a topic someone has dismissed.',
    image: '/images/ai-conversation.webp',
    alt: 'An illustration of someone using an AI chat interface, from my job-talk slides.',
    width: 900, height: 675,
  },
];
